### ISSUE TITLE
GPUize likelihood evaluations checklist

### ISSUE THREAD

**Issue by ptiede** [ptiede/VLBILikelihoods.jl#21]
- [x]  `_unnormed_logpdf_μΣ` make gpuizable
- [x]  `_gaussnorm`
- [ ]  `_closurephasenorm` and its rrule
- [ ]  `unnormed_logpdf` for `RiceLikelihood`
- [ ]  `_cp_logpdf` 
- [ ]  add testing

**Comment by ptiede** [comment]
Mostly handled by Reactant. (still need to deal with a sparse cholesky)
